---
 
- name: restart nginx
  become: yes
  become_method: sudo
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  become: yes
  become_method: sudo
  service: name=nginx state=reloaded
